language: java
script: mvn clean compile dependency-check:check checkstyle:checkstyle
sudo: false

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
